version: '3.4'
services:
  appraisal.api:
    container_name: appraisal_api
    image: tradein/appraisal_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "80"
      - "5002:5002"
    depends_on:
        - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - '/data/db:/data/db'