@startuml
!include Product.puml 
!include AppraisalForm.puml 
class Appraisal
{
    Id
    State
    ExpirationDates
}
 note right: in the context of appraisal product is most likely a product summary \n  

class X    
{
    AppraisedValue 
    PromotionalValue 
    TotalValue
    Appraiser
    Channel
    AppraisedDateTime 
    AppliedPromotions
}

Appraisal o--"1"Product 
note left: Base Value is frozen at this point \n 
Appraisal o--"1..*"X
note right: AppliedPromotions = latest versions of the selected promotions \n 
Appraisal o--"1"AppraisalForm
Product o--"1..*"AppraisalForm
X o--"1..*"AppraisalFormAnswer
AppraisalFormAnswer o--"1..*"AppraisalFormQuestionOption
@enduml