@startuml
!include Product.puml 
!include AppraisalForm.puml 
class Appraisal
{
}
 note right: in the context of appraisal product is most likely a product summary \n  

class AppraisalEvent    
{
    AppraisedValue 
    AppraisedDateTime 
    Appraiser
}

Appraisal o--"1"Product
Appraisal o--"1..*"AppraisalEvent
Appraisal o--"1"AppraisalForm
Product o--"1"AppraisalForm
AppraisalEvent o--"1..*"AppraisalFormAnswer
AppraisalFormAnswer o--"1..*"AppraisalFormQuestionOption
@enduml